apiVersion: v1
kind: Service
metadata:
  name: dotnet-aks
  labels:
    app: dotnet-aks
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: dotnet-aks
    component: netcore-app
  type: LoadBalancer
