on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testmediumacr.azurecr.io
        username: ${{ secrets.acr_testmediumacr_username }}
        password: ${{ secrets.acr_testmediumacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testmediumacr.azurecr.io/dotnetakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push testmediumacr.azurecr.io/dotnetakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dotnetakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dotnetakscluster945d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dotnetakscluster945d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dotnetakscluster945d
        container-registry-url: testmediumacr.azurecr.io
        container-registry-username: ${{ secrets.acr_testmediumacr_username }}
        container-registry-password: ${{ secrets.acr_testmediumacr_password }}
        secret-name: dotnetakscludockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dotnetakscluster945d
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          testmediumacr.azurecr.io/dotnetakscluster:${{ github.sha }}
        imagepullsecrets: |
          dotnetakscludockerauth
